import { strict as assert } from "node:assert";
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, test } from "node:test";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const C_DIR = join(ROOT, "build", "c");
const MANIFEST = join(C_DIR, "source-manifest.json");

interface SourceEntry {
  file: string;
  sha256: string;
}

interface SourceManifest {
  program: string;
  executable: string;
  scriptcVersion: string;
  runtimeVersion: string;
  compiler: { path: string; command: string; version: string };
  target: string | null;
  compileFlags: string[];
  includeDirs: string[];
  typedIr: string;
  typescriptModuleMap: string;
  translationUnits: string[];
  compileDependencies: string[];
  inputs: SourceEntry[];
  files: SourceEntry[];
}

function sha256(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

/**
 * `build/c` is generated and goes stale on any source edit, so a missing or
 * stale snapshot skips rather than fails. Release/CI jobs regenerate it with
 * `yarn emit:c` before the native differential.
 */
function skipReason(): string | false {
  if (!existsSync(MANIFEST)) return "build/c not generated — run `yarn emit:c`";
  const manifest = JSON.parse(readFileSync(MANIFEST, "utf8")) as SourceManifest;
  for (const entry of manifest.inputs) {
    const path = join(ROOT, entry.file);
    if (!existsSync(path) || sha256(path) !== entry.sha256) {
      return `build/c predates a change to ${entry.file} — run \`yarn emit:c\``;
    }
  }
  return false;
}

describe("C inspection intermediary", { skip: skipReason() }, () => {
  test("contains the complete generated program and its linked native sources", () => {
    const manifest = JSON.parse(readFileSync(MANIFEST, "utf8")) as SourceManifest;
    assert.equal(manifest.program, "nat.c");
    assert.equal(manifest.executable, "nat");
    assert.equal(manifest.scriptcVersion, manifest.runtimeVersion);
    assert.equal(manifest.typedIr, "nat.ir.json");
    assert.equal(manifest.typescriptModuleMap, "typescript-module-map.json");
    assert.ok(manifest.translationUnits.includes("nat.c"));
    assert.ok(manifest.translationUnits.includes("runtime/src/scr_lib.c"));
    assert.ok(manifest.translationUnits.includes("runtime/src/scr_child.c"));
    assert.ok(manifest.translationUnits.includes("runtime/vendor/quickjs-ng/libregexp.c"));
    assert.ok(!manifest.translationUnits.includes("runtime/src/scr_island.c"), "no JavaScript engine is linked");
    assert.ok(!manifest.translationUnits.includes("runtime/vendor/quickjs-ng/quickjs.c"), "only the regex library is linked");
    assert.ok(manifest.compileDependencies.includes("runtime/src/scr_runtime.h"));
    assert.equal(
      existsSync(join(C_DIR, "LICENSE")),
      existsSync(join(ROOT, "LICENSE")),
      "the project license, when there is one, accompanies the standalone project",
    );
    assert.ok(existsSync(join(C_DIR, "runtime/vendor/quickjs-ng/LICENSE")), "QuickJS regex notice is retained");
    assert.ok(existsSync(join(C_DIR, "runtime/vendor/ryu/LICENSE-Boost")), "Ryu notice is retained");

    const generated = readFileSync(join(C_DIR, "nat.c"), "utf8");
    assert.ok(generated.startsWith("/* Generated by scriptc"));
    assert.ok(generated.includes("int main(int argc, char **argv)"));
    assert.ok(generated.split("\n").length > 40_000, "nat.c is the full translation unit, not a stub");
    const modules = JSON.parse(readFileSync(join(C_DIR, manifest.typescriptModuleMap), "utf8")) as Record<string, string>;
    assert.ok(Object.values(modules).includes("src/models.ts"));
    assert.ok(Object.values(modules).includes("src/transport.ts"));
    assert.ok(Object.values(modules).includes("src/parsers-sonic.ts"));
    assert.ok(Object.values(modules).includes("src/usage.ts"));

    for (const unit of manifest.translationUnits) {
      assert.ok(existsSync(join(C_DIR, unit)), `missing linked source: ${unit}`);
    }
    for (const dependency of manifest.compileDependencies) {
      assert.ok(existsSync(join(C_DIR, dependency)), `missing compile dependency: ${dependency}`);
    }
  });

  test("hashes every captured source and records the actual compile recipe", () => {
    const manifest = JSON.parse(readFileSync(MANIFEST, "utf8")) as SourceManifest;
    assert.ok(manifest.inputs.some((entry) => entry.file === "cli/nat.ts"));
    assert.ok(manifest.inputs.some((entry) => entry.file === "src/transport.ts"));
    // Freshness is the suite's skip condition, checked once above; what is
    // asserted here is that every input the snapshot names actually exists.
    for (const entry of manifest.inputs) {
      assert.ok(existsSync(join(ROOT, entry.file)), `missing TypeScript input: ${entry.file}`);
    }

    assert.ok(manifest.files.length > manifest.translationUnits.length, "transitive headers are captured too");
    for (const entry of manifest.files) {
      const path = join(C_DIR, entry.file);
      assert.ok(existsSync(path), `missing manifest file: ${entry.file}`);
      assert.equal(sha256(path), entry.sha256, `hash mismatch: ${entry.file}`);
    }

    const invocations = JSON.parse(readFileSync(join(C_DIR, "compiler-invocations.json"), "utf8")) as {
      compiler: string;
      arguments: string[];
    }[];
    assert.ok(invocations.some((entry) => entry.arguments.includes("<repo>/build/c/nat.c")));
    assert.ok(invocations.some((entry) => entry.arguments.includes("<scriptc-runtime>/src/scr_child.c")));
  });

  test("ships a Makefile that rebuilds the snapshot with the recorded recipe", () => {
    const manifest = JSON.parse(readFileSync(MANIFEST, "utf8")) as SourceManifest;
    // The recipe is lifted from the trace, not hand-written, so a change in how
    // scriptc links shows up here instead of silently drifting.
    assert.ok(manifest.compileFlags.includes("-std=c11"), "the real flags were captured");
    assert.ok(manifest.compiler.path.startsWith("/"), "the exact compiler path is retained for provenance");
    assert.ok(
      manifest.compiler.command === "cc" || manifest.compiler.command === "zig cc",
      "the standalone recipe uses a portable compiler command",
    );
    assert.ok(manifest.includeDirs.includes("runtime/src"), "include roots are relative to the snapshot");
    for (const flag of manifest.compileFlags) {
      assert.ok(!flag.endsWith(".c") && !flag.endsWith(".o"), `path leaked into compileFlags: ${flag}`);
      assert.ok(flag !== "-o" && flag !== "-I", "option/value pairs are stripped in full");
    }

    const linked = readFileSync(join(C_DIR, "linked-sources.txt"), "utf8").trim().split("\n");
    assert.deepEqual(linked, manifest.translationUnits, "the file list and the manifest agree");

    const makefile = readFileSync(join(C_DIR, "Makefile"), "utf8");
    // `?=` cannot set CC: make predefines it, so the assignment would be a
    // silent no-op and the snapshot would build with the wrong compiler.
    assert.match(makefile, /^CC = /m);
    assert.ok(!/^CC \?=/m.test(makefile), "CC must not use ?=, which make ignores for predefined variables");
    for (const unit of manifest.translationUnits) {
      assert.ok(makefile.includes(unit), `Makefile is missing ${unit}`);
    }
    assert.ok(makefile.includes("$(SOURCES) $(DEPENDENCIES)"), "header edits must trigger a rebuild");
    for (const dependency of manifest.compileDependencies) {
      assert.ok(makefile.includes(dependency), `Makefile is missing dependency ${dependency}`);
    }
    assert.ok(manifest.files.some((entry) => entry.file === "Makefile"), "the Makefile is hash-pinned too");
  });
});
