/**
 * The SSH transport, driven by the system `ssh` binary.
 *
 * The compiled runtime has no hash/cipher/KEX primitives, so nat drives
 * OpenSSH, which also brings the legacy KEX/ciphers old network gear needs,
 * ProxyJump, known_hosts, agent support and the user's own ssh_config.
 *
 * One host gets one connection for the whole run:
 *
 *   - a master process (`ssh -M -N`) authenticates once and holds the socket;
 *   - `exec()` runs each command over that socket (`ssh -o ControlPath=…`);
 *   - `openShell()` opens one interactive `ssh -tt` session on the same socket.
 *
 * `--no-multiplex` drops the master and gives every command its own connection,
 * for devices that permit only one session per connection.
 *
 * Piped stdin is not part of the compiled `spawn` surface, so the interactive
 * shell feeds the ssh child through a FIFO that a `/bin/sh` wrapper redirects
 * into it. Writes are incremental, which is what live prompt detection (and so
 * conditionals and CLI sub-modes) depends on.
 *
 * Passwords never appear in an argv or on disk: a generated askpass helper in a
 * 0700 temp directory prints whichever secret its prompt asks for, and the
 * secrets ride the ssh child's environment.
 */

import { spawn } from "node:child_process";
import type { ChildProcess } from "node:child_process";
import { chmodSync, closeSync, existsSync, mkdtempSync, openSync, rmSync, writeFileSync, writeSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { HostConfig } from "./models.ts";
import { ChildProcessRegistry, ProcessResult, childEnv, runProcess, runProcessSync, sleep } from "./process.ts";

export class ConnectionError extends Error {}

/** ssh's own failure code — anything else is the remote command's status. */
export const SSH_ERROR_EXIT = 255;
const MAX_PROMPT_SECRETS = 16;

const ASKPASS_SCRIPT = `#!/bin/sh
# Generated by nat. Prints the secret ssh asks for; the value itself arrives
# through the environment, never through a file or an argv.
answer_marker() {
  [ -n "$2" ] || return 1
  case "$1" in
    *"$2"*) printf '%s\\n' "$3"; exit 0 ;;
  esac
  return 1
}
answer_marker "$1" "\${NAT_ASKPASS_MARKER_0-}" "\${NAT_ASKPASS_SECRET_0-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_1-}" "\${NAT_ASKPASS_SECRET_1-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_2-}" "\${NAT_ASKPASS_SECRET_2-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_3-}" "\${NAT_ASKPASS_SECRET_3-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_4-}" "\${NAT_ASKPASS_SECRET_4-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_5-}" "\${NAT_ASKPASS_SECRET_5-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_6-}" "\${NAT_ASKPASS_SECRET_6-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_7-}" "\${NAT_ASKPASS_SECRET_7-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_8-}" "\${NAT_ASKPASS_SECRET_8-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_9-}" "\${NAT_ASKPASS_SECRET_9-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_10-}" "\${NAT_ASKPASS_SECRET_10-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_11-}" "\${NAT_ASKPASS_SECRET_11-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_12-}" "\${NAT_ASKPASS_SECRET_12-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_13-}" "\${NAT_ASKPASS_SECRET_13-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_14-}" "\${NAT_ASKPASS_SECRET_14-}"
answer_marker "$1" "\${NAT_ASKPASS_MARKER_15-}" "\${NAT_ASKPASS_SECRET_15-}"
case "$1" in
  *[Pp]assphrase*) printf '%s\\n' "$NAT_ASKPASS_PASSPHRASE" ;;
  *) printf '%s\\n' "$NAT_ASKPASS_PASSWORD" ;;
esac
`;

/** Redirects the FIFO into the ssh child: `sh -c '…' <ssh> <args…>`. */
const STDIN_WRAPPER = 'exec "$0" "$@" < "$NAT_STDIN_FIFO"';

/** Process-wide transport settings, shared by every host in a run. */
export class TransportOptions {
  /** The ssh executable; `NAT_SSH_BIN` overrides it (tests point at a stub). */
  sshBin: string;
  /** Path passed to `ssh -F`, or "" to let ssh read its own default config. */
  configPath: string;
  connectTimeout: number;
  /** yes | no | accept-new | ask */
  hostKeyChecking: string;
  multiplex: boolean;
  /** Extra `-o Key=Value` settings from `--ssh-option`. */
  extraOptions: string[];
  verbose: boolean;

  constructor() {
    const bin = process.env["NAT_SSH_BIN"];
    this.sshBin = bin === undefined || bin === "" ? "ssh" : bin;
    this.configPath = "";
    this.connectTimeout = 20;
    this.hostKeyChecking = "accept-new";
    this.multiplex = true;
    this.extraOptions = [];
    this.verbose = false;
  }
}

/**
 * The private working directory for one nat process: control sockets, command
 * FIFOs and the askpass helper. Created 0700 and removed on the way out.
 */
export class TransportWorkspace {
  dir: string;
  askpassPath: string;
  private counter: number;
  private connections: SshConnection[];
  private channels: ShellChannel[];
  childProcesses: ChildProcessRegistry;

  constructor() {
    this.dir = mkdtempSync(join(tmpdir(), "nat-"));
    this.askpassPath = join(this.dir, "askpass");
    this.counter = 0;
    this.connections = [];
    this.channels = [];
    this.childProcesses = new ChildProcessRegistry();
    writeFileSync(this.askpassPath, ASKPASS_SCRIPT);
    chmodSync(this.askpassPath, 0o700);
  }

  /** A fresh path inside the workspace. */
  reserve(suffix: string): string {
    this.counter += 1;
    return join(this.dir, `${this.counter}${suffix}`);
  }

  addConnection(connection: SshConnection): void {
    if (!this.connections.includes(connection)) this.connections.push(connection);
  }

  removeConnection(connection: SshConnection): void {
    const index = this.connections.indexOf(connection);
    if (index >= 0) this.connections.splice(index, 1);
  }

  addChannel(channel: ShellChannel): void {
    if (!this.channels.includes(channel)) this.channels.push(channel);
  }

  removeChannel(channel: ShellChannel): void {
    const index = this.channels.indexOf(channel);
    if (index >= 0) this.channels.splice(index, 1);
  }

  /** Kill every child before removing its sockets/FIFOs. Safe more than once. */
  dispose(): void {
    this.childProcesses.terminateAll();
    for (const channel of this.channels.slice()) channel.end();
    for (const connection of this.connections.slice()) connection.close();
    this.channels = [];
    this.connections = [];
    try {
      rmSync(this.dir, { recursive: true, force: true });
    } catch (err) {
      // A leftover socket in a private temp directory is not worth failing on.
    }
  }
}

/** Everything one connection needs beyond the shared options. */
export class ConnectionTarget {
  host: HostConfig;
  /** Password for this host, or "" when none is available. */
  password: string;
  /** Key passphrase for this host, or "". */
  passphrase: string;
  /** ProxyJump override; "" keeps the host's own ProxyJump. */
  jumpOverride: string;
  /** Login user override; "" keeps ssh_config's resolved user. */
  userOverride: string;
  /** Port override from an explicit jump token; -1 keeps ssh_config's port. */
  portOverride: number;
  /** Prompt fragments and per-hop secrets used by ProxyJump child clients. */
  promptMarkers: string[];
  promptSecrets: string[];

  constructor(host: HostConfig) {
    this.host = host;
    this.password = "";
    this.passphrase = "";
    this.jumpOverride = "";
    this.userOverride = "";
    this.portOverride = -1;
    this.promptMarkers = [];
    this.promptSecrets = [];
  }

  effectiveUser(): string {
    // Configured users stay in ssh_config for the same reason as Port and
    // IdentityFile: ssh may select them through criteria nat cannot evaluate.
    // Only an explicit runtime override is put in the destination argv.
    return this.userOverride;
  }

  effectiveJump(): string {
    // A configured ProxyJump is left in ssh_config so ssh evaluates it with
    // its full Match/token semantics. Only an explicit nat override belongs on
    // the command line.
    return this.jumpOverride;
  }

  hasSecret(): boolean {
    if (this.password !== "" || this.passphrase !== "") return true;
    for (const secret of this.promptSecrets) {
      if (secret !== "") return true;
    }
    return false;
  }

  /** Associate an askpass prompt fragment with a secret (which may be empty). */
  addPromptSecret(marker: string, secret: string): void {
    if (marker === "") return;
    const existing = this.promptMarkers.indexOf(marker);
    if (existing >= 0) {
      if (this.promptSecrets[existing] === "" && secret !== "") this.promptSecrets[existing] = secret;
      return;
    }
    if (this.promptMarkers.length >= MAX_PROMPT_SECRETS) return;
    this.promptMarkers.push(marker);
    this.promptSecrets.push(secret);
  }
}

/** Split one `ssh -G` output line into its lower-case keyword and value. */
function effectiveConfigLine(line: string): string[] {
  const trimmed = line.trim();
  let space = -1;
  for (let i = 0; i < trimmed.length; i += 1) {
    if (!/\s/.test(trimmed.charAt(i))) continue;
    space = i;
    break;
  }
  if (space < 1) return [];
  return [trimmed.slice(0, space).toLowerCase(), trimmed.slice(space + 1).trim()];
}

/**
 * Resolve the connection fields with `ssh -G`, which evaluates the config
 * exactly as the connection will: `Match exec`, `Match localuser`,
 * canonical/final passes, every Include form, and the implicit local username.
 * Stored credentials are keyed by alias + this effective user. Only the driver
 * comes from nat's own reader.
 */
export function resolveEffectiveHost(
  options: TransportOptions,
  host: HostConfig,
  userOverride: string,
  portOverride: number,
  jumpOverride: string,
): HostConfig {
  const args: string[] = ["-G"];
  if (options.configPath !== "") args.push("-F", options.configPath);
  if (portOverride > 0 && portOverride <= 65535) args.push("-p", `${portOverride}`);
  if (jumpOverride !== "") args.push("-J", jumpOverride);
  for (const option of options.extraOptions) args.push("-o", option);
  const alias = host.alias === "" ? host.hostname : host.alias;
  args.push(userOverride === "" ? alias : `${userOverride}@${alias}`);

  const result = runProcessSync(options.sshBin, args, "", process.env, 10_000);
  if (!result.ok()) throw new ConnectionError(`ssh -G ${alias} failed: ${result.output.trim()}`);

  const effective = new HostConfig(host.alias);
  effective.targetOs = host.targetOs;
  let sawHostname = false;
  let sawUser = false;
  let sawPort = false;
  for (const line of result.stdout.split(/\r?\n/)) {
    const pair = effectiveConfigLine(line);
    if (pair.length !== 2) continue;
    const key = pair[0];
    const value = pair[1];
    if (key === "hostname" && value !== "") {
      effective.hostname = value;
      sawHostname = true;
    } else if (key === "user" && value !== "") {
      effective.user = value;
      sawUser = true;
    } else if (key === "port") {
      const parsed = Number(value);
      if (Number.isFinite(parsed) && parsed > 0 && parsed <= 65535) {
        effective.port = Math.trunc(parsed);
        sawPort = true;
      }
    } else if (key === "identityfile" && value !== "" && value.toLowerCase() !== "none") {
      effective.identityFiles.push(value);
    } else if (key === "identitiesonly") {
      effective.identitiesOnly = value.toLowerCase() === "yes";
    } else if (key === "proxyjump") {
      effective.proxyJump = value.toLowerCase() === "none" ? "" : value;
    }
  }

  if (!sawHostname || !sawUser || !sawPort) {
    throw new ConnectionError(`ssh -G ${alias} did not report a hostname, user and port (is ${options.sshBin} OpenSSH?)`);
  }
  return effective;
}

/** Split a ProxyJump specification into its hops. */
export function splitJumpSpec(spec: string): string[] {
  const hops: string[] = [];
  for (const raw of spec.split(",")) {
    const hop = raw.trim();
    if (hop !== "") hops.push(hop);
  }
  return hops;
}

/** The auth methods nat was able to offer, for the failure message. */
function offeredMethods(target: ConnectionTarget): string[] {
  const methods: string[] = [];
  if (target.host.identityFiles.length > 0) methods.push("key");
  const agent = process.env["SSH_AUTH_SOCK"];
  if (!target.host.identitiesOnly && agent !== undefined && agent !== "") methods.push("agent");
  if (target.password !== "") methods.push("password");
  return methods;
}

/**
 * Turn an ssh failure into the message nat reports. Authentication failures name
 * what was tried and how to add a method.
 */
export function connectErrorMessage(target: ConnectionTarget, result: ProcessResult): string {
  const label = target.host.alias !== "" ? target.host.alias : target.host.hostname;
  const stderr = result.stderr.trim();
  const detail = stderr === "" ? result.output.trim() : stderr;
  const lines = detail === "" ? [] : detail.split(/\r?\n/);
  const lastLine = lines.length === 0 ? "" : lines[lines.length - 1].trim();

  if (result.spawnError !== "") {
    return `Failed connecting to ${label}: cannot run ssh (${result.spawnError})`;
  }
  if (result.timedOut) {
    return `Failed connecting to ${label}: connection timed out`;
  }
  if (!/permission denied|authentication/i.test(detail)) {
    return `Failed connecting to ${label}: ${lastLine === "" ? "ssh exited without a reason" : lastLine}`;
  }

  const methods = offeredMethods(target);
  const tried = methods.length > 0 ? `tried ${methods.join(", ")}` : "no auth methods available";
  const hints: string[] = [];
  if (!methods.includes("key") && !methods.includes("agent")) {
    hints.push("add an IdentityFile or start ssh-agent");
  }
  if (!methods.includes("password")) {
    hints.push(`store a password with \`nat cred set ${label}\``);
  }
  const hint = hints.length > 0 ? ` — ${hints.join("; ")}` : "";
  return `Failed connecting to ${label}: authentication failed (${tried})${hint}`;
}

/** One live interactive shell session, fed incrementally through a FIFO. */
export class ShellChannel {
  child: ChildProcess;
  /** Everything the session has emitted since the last `take()`. */
  buf: string;
  closed: boolean;
  /** Wrapper exit status, or -1 while it is running / after a signal. */
  exitCode: number;
  /** Non-empty only when the wrapper itself could not be spawned. */
  spawnError: string;
  private fd: number;
  private fifoPath: string;
  private workspace: TransportWorkspace;

  constructor(child: ChildProcess, fd: number, fifoPath: string, workspace: TransportWorkspace) {
    this.child = child;
    this.buf = "";
    this.closed = child.exitCode !== null;
    this.exitCode = child.exitCode === null ? -1 : child.exitCode;
    this.spawnError = "";
    this.fd = fd;
    this.fifoPath = fifoPath;
    this.workspace = workspace;
    workspace.addChannel(this);

    const out = child.stdout;
    if (out !== null) {
      out.on("data", (chunk: Buffer) => {
        this.buf += chunk.toString("utf8");
      });
    }
    const err = child.stderr;
    if (err !== null) {
      err.on("data", (chunk: Buffer) => {
        this.buf += chunk.toString("utf8");
      });
    }
    child.on("error", (err: Error) => {
      this.spawnError = err.message;
      this.closed = true;
    });
    child.on("exit", (code: number | null) => {
      this.exitCode = code === null ? -1 : code;
      this.closed = true;
    });
  }

  hasData(): boolean {
    return this.buf.length > 0;
  }

  /** Take everything buffered so far, leaving the buffer empty. */
  take(): string {
    const data = this.buf;
    this.buf = "";
    return data;
  }

  sendLine(command: string, newline: string): void {
    if (this.closed) return;
    try {
      writeSync(this.fd, command + newline);
    } catch (err) {
      this.closed = true;
    }
  }

  /** Close the session's stdin and stop the ssh client. */
  end(): void {
    try {
      closeSync(this.fd);
    } catch (err) {
      // Already closed.
    }
    try {
      this.child.kill("SIGTERM");
    } catch (err) {
      // Already reaped.
    }
    try {
      if (existsSync(this.fifoPath)) rmSync(this.fifoPath, { force: true });
    } catch (err) {
      // The workspace teardown removes it either way.
    }
    this.closed = true;
    this.workspace.removeChannel(this);
  }
}

/**
 * One host's connection. `open()` authenticates; `exec()` and `openShell()` run
 * work over it; `close()` tears it down.
 */
export class SshConnection {
  options: TransportOptions;
  workspace: TransportWorkspace;
  target: ConnectionTarget;
  /** The ControlPath socket, or "" when multiplexing is off. */
  controlPath: string;
  private master: ChildProcess | null;
  private masterOutput: string;
  private masterExited: boolean;
  private masterExitCode: number;
  private masterSpawnError: string;

  constructor(options: TransportOptions, workspace: TransportWorkspace, target: ConnectionTarget) {
    this.options = options;
    this.workspace = workspace;
    this.target = target;
    this.controlPath = "";
    this.master = null;
    this.masterOutput = "";
    this.masterExited = false;
    this.masterExitCode = 0;
    this.masterSpawnError = "";
    workspace.addConnection(this);
  }

  /**
   * The destination argument: an explicitly overridden `user@alias`, or just
   * the alias so ssh_config chooses the configured user.
   *
   * Keeping the original alias is important: ssh applies `Host leaf1` rules to
   * the destination token, then resolves HostName itself. Passing nat's already
   * resolved IP here would bypass every option in that block that nat does not
   * model explicitly (legacy KEX/ciphers, ProxyCommand, CertificateFile, and
   * so on). A literal IP/FQDN has alias === hostname, so it is unchanged.
   */
  destination(): string {
    const user = this.target.effectiveUser();
    const host = this.target.host.alias === "" ? this.target.host.hostname : this.target.host.alias;
    return user === "" ? host : `${user}@${host}`;
  }

  /** The environment an ssh child runs in: askpass wiring plus the secrets. */
  private sshEnv(extraFifo: string): { [k: string]: string | undefined } {
    const extra = new Map<string, string>();
    if (this.target.hasSecret()) {
      extra.set("SSH_ASKPASS", this.workspace.askpassPath);
      extra.set("SSH_ASKPASS_REQUIRE", "force");
      extra.set("NAT_ASKPASS_PASSWORD", this.target.password);
      extra.set("NAT_ASKPASS_PASSPHRASE", this.target.passphrase);
      for (let i = 0; i < this.target.promptMarkers.length && i < MAX_PROMPT_SECRETS; i += 1) {
        extra.set(`NAT_ASKPASS_MARKER_${i}`, this.target.promptMarkers[i]);
        extra.set(`NAT_ASKPASS_SECRET_${i}`, this.target.promptSecrets[i]);
      }
    }
    if (extraFifo !== "") extra.set("NAT_STDIN_FIFO", extraFifo);
    return childEnv(extra);
  }

  /** The `-o` settings and flags every ssh invocation for this host carries. */
  private baseArgs(): string[] {
    const args: string[] = [];
    if (this.options.configPath !== "") args.push("-F", this.options.configPath);
    args.push("-o", `ConnectTimeout=${Math.max(1, this.options.connectTimeout)}`);
    args.push("-o", "ServerAliveInterval=15");
    args.push("-o", "ServerAliveCountMax=3");
    args.push("-o", `StrictHostKeyChecking=${this.options.hostKeyChecking}`);
    args.push("-o", "LogLevel=ERROR");
    if (this.target.hasSecret()) {
      args.push("-o", "BatchMode=no");
      args.push("-o", "NumberOfPasswordPrompts=1");
      args.push("-o", "KbdInteractiveAuthentication=yes");
    } else {
      // Without a secret there is nothing to answer a prompt with; failing fast
      // beats a run that hangs on an invisible password question.
      args.push("-o", "BatchMode=yes");
    }

    // Port, IdentityFile, IdentitiesOnly and the configured ProxyJump remain in
    // the config file. Re-spelling them as argv options would override ssh's
    // own Match/token expansion (`IdentityFile none`, `%d`, `%h`, etc.). Only a
    // port explicitly embedded in a --jump-shell token belongs on argv.
    if (this.target.portOverride > 0) args.push("-p", `${this.target.portOverride}`);
    const jump = this.target.effectiveJump();
    if (jump !== "") args.push("-J", jump);

    // OpenSSH keeps the first value for most repeated `-o` settings. The
    // control path and its lifetime are nat's private coordination primitives,
    // so both must precede user-supplied options; otherwise a conflicting
    // ControlPath makes ssh and nat wait on different sockets, or
    // ControlPersist can leave a background master behind after teardown.
    if (this.controlPath !== "") {
      args.push("-o", `ControlPath=${this.controlPath}`);
      args.push("-o", "ControlPersist=no");
    }
    for (const option of this.options.extraOptions) args.push("-o", option);
    return args;
  }

  private trace(args: string[]): void {
    if (!this.options.verbose) return;
    process.stderr.write(`nat: ${this.options.sshBin} ${args.join(" ")}\n`);
  }

  /**
   * Authenticate and hold the connection open. With multiplexing off this only
   * validates that ssh exists; the first command surfaces any auth failure.
   */
  async open(): Promise<void> {
    if (!this.options.multiplex) return;

    // `open()` may be retried after a failed authentication. Do not let the
    // prior child's exit flag or stderr make the retry fail before it starts.
    this.masterOutput = "";
    this.masterExited = false;
    this.masterExitCode = 0;
    this.masterSpawnError = "";
    this.controlPath = this.workspace.reserve(".sock");
    const args = this.baseArgs();
    args.push("-M", "-N");
    args.push("-o", "ControlMaster=yes");
    args.push(this.destination());
    this.trace(args);

    const child = spawn(this.options.sshBin, args, { stdio: ["ignore", "pipe", "pipe"], env: this.sshEnv("") });
    this.master = child;

    const out = child.stdout;
    if (out !== null) {
      out.on("data", (chunk: Buffer) => {
        this.masterOutput += chunk.toString("utf8");
      });
    }
    const err2 = child.stderr;
    if (err2 !== null) {
      err2.on("data", (chunk: Buffer) => {
        this.masterOutput += chunk.toString("utf8");
      });
    }
    child.on("error", (spawnErr: Error) => {
      this.masterOutput += spawnErr.message;
      this.masterSpawnError = spawnErr.message;
      this.masterExited = true;
      this.masterExitCode = SSH_ERROR_EXIT;
    });
    child.on("exit", (code: number | null) => {
      this.masterExited = true;
      this.masterExitCode = code === null ? SSH_ERROR_EXIT : code;
    });

    // The socket appears once authentication succeeds. Polling for it — rather
    // than for a fixed delay — keeps a fast connection fast and a slow one
    // honest, and the master's own exit ends the wait immediately.
    const deadline = Date.now() + (Math.max(1, this.options.connectTimeout) + 10) * 1000;
    while (Date.now() < deadline) {
      if (existsSync(this.controlPath)) return;
      if (this.masterExited) break;
      await sleep(50);
    }

    const failure = new ProcessResult();
    failure.code = this.masterExitCode;
    failure.stderr = this.masterOutput;
    failure.output = this.masterOutput;
    failure.spawnError = this.masterSpawnError;
    failure.timedOut = !this.masterExited;
    this.master = null;
    try {
      child.kill("SIGKILL");
    } catch (err) {
      // Already gone.
    }
    if (failure.timedOut) {
      throw new ConnectionError(
        `Failed connecting to ${this.target.host.alias}: timed out after ${this.options.connectTimeout}s`,
      );
    }
    throw new ConnectionError(connectErrorMessage(this.target, failure));
  }

  /** Run one command over the connection; stdout and stderr interleave into one transcript. */
  async exec(command: string, timeoutSeconds: number): Promise<ProcessResult> {
    const args = this.baseArgs();
    // A direct flag wins over both ssh_config and `--ssh-option RequestTTY=…`,
    // preserving the unmodified exec-channel transcript this path promises.
    args.push("-T");
    args.push(this.destination());
    args.push("--", command);
    this.trace(args);
    const result = await runProcess(
      this.options.sshBin,
      args,
      this.sshEnv(""),
      Math.max(1, timeoutSeconds) * 1000,
      this.workspace.childProcesses,
    );
    if (result.code === SSH_ERROR_EXIT && !this.options.multiplex) {
      throw new ConnectionError(connectErrorMessage(this.target, result));
    }
    return result;
  }

  /** Turn a shell wrapper's early exit into the normal connection diagnostic. */
  shellFailure(transcript: string, channel: ShellChannel): ConnectionError {
    const result = new ProcessResult();
    result.code = channel.exitCode;
    result.output = transcript;
    result.stderr = transcript;
    result.spawnError = channel.spawnError;
    return new ConnectionError(connectErrorMessage(this.target, result));
  }

  /** Open the interactive session: one `ssh -tt` reading from a private FIFO. */
  async openShell(): Promise<ShellChannel> {
    const fifoPath = this.workspace.reserve(".fifo");
    const mkfifo = await runProcess(
      "mkfifo",
      [fifoPath],
      childEnv(new Map<string, string>()),
      10000,
      this.workspace.childProcesses,
    );
    if (!mkfifo.ok()) {
      throw new ConnectionError(
        `Failed opening an interactive session to ${this.target.host.alias}: mkfifo failed (${mkfifo.output.trim()})`,
      );
    }

    const args = this.baseArgs();
    args.push("-tt");
    args.push(this.destination());
    this.trace(args);

    const wrapperArgs: string[] = ["-c", STDIN_WRAPPER, this.options.sshBin];
    for (const arg of args) wrapperArgs.push(arg);

    const child = spawn("/bin/sh", wrapperArgs, { stdio: ["ignore", "pipe", "pipe"], env: this.sshEnv(fifoPath) });

    // Opening the FIFO read-write never blocks, so a child that dies before it
    // reaches the redirect cannot wedge the parent here.
    let fd = -1;
    try {
      fd = openSync(fifoPath, "r+");
    } catch (err) {
      try {
        child.kill("SIGKILL");
      } catch (err2) {
        // Already gone.
      }
      const detail = err instanceof Error ? err.message : "open failed";
      throw new ConnectionError(`Failed opening an interactive session to ${this.target.host.alias}: ${detail}`);
    }
    return new ShellChannel(child, fd, fifoPath, this.workspace);
  }

  /** Release the connection. Safe to call more than once. */
  close(): void {
    if (this.controlPath !== "" && existsSync(this.controlPath)) {
      const args = this.baseArgs();
      args.push("-O", "exit", this.destination());
      // Fire-and-forget: the master also exits when its child is killed below.
      const closer = spawn(this.options.sshBin, args, { stdio: ["ignore", "ignore", "ignore"], env: this.sshEnv("") });
      closer.on("error", () => {
        // Killing the master below is enough.
      });
      closer.unref();
    }
    const master = this.master;
    if (master !== null) {
      try {
        master.kill("SIGTERM");
      } catch (err) {
        // Already reaped.
      }
      this.master = null;
    }
    this.workspace.removeConnection(this);
  }
}
